version : '3'
services:
    web:
        build:
            context: . #specifies where the files should be pulled from
            dockerfile: Dockerfile.dev #loc of the dockerfile
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
    tests:
        build:
            context: . 
            dockerfile: Dockerfile.dev 
        volumes:
            - /app/node_modules #stating to not change this directory
            - .:/app #stating to take the current build dir (.) and post it into /app
        command: ["npm", "run", "test"]